---
# Play to create and provision instance.
- name: "Converge"
  hosts: "all"
  tasks:
    - name: "Include unattended_upgrades role"
      ansible.builtin.include_role:
        name: "hifis.software_services.unattended_upgrades"

...
