# SPDX-FileCopyrightText: Helmholtz Centre for Environmental Research (UFZ)
# SPDX-FileCopyrightText: Helmholtz-Zentrum Dresden-Rossendorf (HZDR)
#
# SPDX-License-Identifier: Apache-2.0

---
dependency:
  name: "galaxy"
driver:
  name: "podman"
platforms:
  - name: "instance"
    image: "${MOLECULE_IMAGE:-ghcr.io/hifis-net/ubuntu-systemd:24.04}"
    pre_build_image: true
    privileged: true
    override_command: false
    systemd: true
    tty: true
provisioner:
  name: "ansible"
  options:
    diff: true
  inventory:
    hosts:
      all:
        vars:
          unattended_autofix_interrupted_dpkg: false
          unattended_minimal_steps: true
          unattended_install_on_shutdown: true
          unattended_automatic_reboot: true
          unattended_update_days: '{"Sat"}'
          unattended_remove_unused_kernel_packages: true
          unattended_only_on_ac_power: true
          unattended_mail_sender: "jane@example.org"
          unattended_systemd_timer_override: true
          unattended_apt_daily_oncalendar: "*-*-* 11:08"
          unattended_apt_daily_randomizeddelaysec: "0s"
          unattended_apt_daily_upgrade_oncalendar: "*-*-* 11:31"
          unattended_apt_daily_upgrade_randomizeddelaysec: "0s"
  playbooks:
    prepare: "prepare.yml"
    check: "converge.yml"
    converge: "converge.yml"
    verify: "verify.yml"
verifier:
  name: "ansible"
scenario:
  test_sequence:
    - "destroy"
    - "dependency"
    - "syntax"
    - "create"
    - "prepare"
    - "check"
    - "converge"
    - "idempotence"
    - "check"
    - "side_effect"
    - "verify"
    - "destroy"

...
