---
# Play to install dependencies.
- name: "Prepare"
  hosts: "all"
  tasks:
    - name: "Install dependencies"
      ansible.builtin.apt:
        update_cache: "yes"
        force_apt_get: "yes"

...
