# SPDX-FileCopyrightText: Helmholtz Centre for Environmental Research (UFZ)
# SPDX-FileCopyrightText: Helmholtz-Zentrum Dresden-Rossendorf (HZDR)
#
# SPDX-License-Identifier: Apache-2.0

---
- name: "Prepare"
  hosts: "all"
  tasks:
    - name: "Install dependencies"
      ansible.builtin.apt:
        name:
          - "sudo"      # for `become` privilege escalation
          - "iproute2"  # for gathering network facts
          - "udev"      # needed for netplan
        update_cache: true
        state: "present"

    - name: "Ensure systemd-udevd is started on Ubuntu 24.04"
      ansible.builtin.service:
        name: "systemd-udevd"
        state: "started"
      when: "ansible_facts.distribution_release | lower == 'noble'"
...
