# SPDX-FileCopyrightText: Helmholtz Centre for Environmental Research (UFZ)
# SPDX-FileCopyrightText: Helmholtz-Zentrum Dresden-Rossendorf (HZDR)
#
# SPDX-License-Identifier: Apache-2.0

[project]
name = "ansible-collection-toolkit"
version = "7.0.1"
description = "This collection provides production-ready Ansible roles used for providing services used in research and by research software engineers, but not exclusively."
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "ansible>=14.5.0",
]

[dependency-groups]
dev = [
    "ansible-lint>=26.9.0",
    "antsibull-nox>=1.9.3",
    "molecule>=26.9.0",
    "molecule-plugins[podman]>=26.9.28",
    "netaddr>=1.3.0",
    "nox>=2025.5.1",
    "reuse>=6.2.0",
    "yamllint>=1.38.0",
]
