# SPDX-FileCopyrightText: Helmholtz Centre for Environmental Research (UFZ)
# SPDX-FileCopyrightText: Helmholtz-Zentrum Dresden-Rossendorf (HZDR)
#
# SPDX-License-Identifier: MIT

---
- name: "Prepare"
  hosts: "all"
  become: true
  vars:
    # Apply suggested Elasticsearch configuration
    elasticsearch_version: "8.x"
    elasticsearch_package: "elasticsearch"
    elasticsearch_heap_size_min: "256m"
    elasticsearch_heap_size_max: "256m"
    elasticsearch_extra_options: |
      xpack.security.enabled: false
      xpack.security.http.ssl.enabled: false
      xpack.security.transport.ssl.enabled: false
      http.max_content_length: 400mb
      indices.query.bool.max_clause_count: 2000

  tasks:

    - name: "Install required packages"
      when: "ansible_facts.os_family == 'Debian'"
      ansible.builtin.apt:
        name:
          - "sudo"
          - "gpg"
          - "ca-certificates"
          - "python3-cryptography"
          - "python3-debian"
          - "ssl-cert"
        state: "present"
        update_cache: true

    - name: "Provide SSL/TLS certificate on AlmaLinux"
      when: "ansible_facts.os_family == 'RedHat'"
      block:
        - name: "Ensure SSL/TLS directories exist"
          ansible.builtin.file:
            path: "{{ item }}"
            state: "directory"
            mode: '0755'
          loop:
            - "/etc/ssl/private"
            - "/etc/ssl/certs"

        - name: "Install python-cryptography"
          ansible.builtin.pip:
            name: "cryptography"

        - name: "Create RSA private key"
          community.crypto.openssl_privatekey:
            path: "/etc/ssl/private/ssl-cert-snakeoil.key"
            size: 2048
            type: "RSA"
            mode: '0600'

        - name: "Create a snakeoil certificate"
          community.crypto.x509_certificate:
            path: "/etc/ssl/certs/ssl-cert-snakeoil.pem"
            privatekey_path: "/etc/ssl/private/ssl-cert-snakeoil.key"
            provider: "selfsigned"
            selfsigned_not_after: "+365d"
            mode: '0644'

    - name: "Include geerlingguy.elasticsearch"
      ansible.builtin.include_role:
        name: "geerlingguy.elasticsearch"

    - name: "Include geerlingguy.postgresql"
      ansible.builtin.include_role:
        name: "geerlingguy.postgresql"
