# SPDX-FileCopyrightText: Helmholtz Centre for Environmental Research (UFZ)
# SPDX-FileCopyrightText: Helmholtz-Zentrum Dresden-Rossendorf (HZDR)
#
# SPDX-License-Identifier: MIT

---

collections:
  - name: "community.crypto"
    version: "2.20.0"

roles:
  - src: "geerlingguy.elasticsearch"
    version: "5.1.2"

  - src: "geerlingguy.postgresql"
    version: "3.5.2"
