# SPDX-FileCopyrightText: Helmholtz Centre for Environmental Research (UFZ)
# SPDX-FileCopyrightText: Helmholtz-Zentrum Dresden-Rossendorf (HZDR)
# SPDX-FileCopyrightText: Jan Vlnas
#
# SPDX-License-Identifier: GPL-2.0-or-later

---
# handlers file for unattended-upgrades

- name: 'Restart apt-daily timer'
  ansible.builtin.systemd:
    daemon_reload: true
    name: 'apt-daily.timer'
    state: 'restarted'
    enabled: true

- name: 'Restart apt-daily-upgrade timer'
  ansible.builtin.systemd:
    daemon_reload: true
    name: 'apt-daily-upgrade.timer'
    state: 'restarted'
    enabled: true
...
