---
# handlers file for unattended-upgrades

- name: 'Restart apt-daily timer'
  ansible.builtin.systemd:
    daemon_reload: true
    name: 'apt-daily.timer'
    state: 'restarted'
    enabled: yes

- name: 'Restart apt-daily-upgrade timer'
  ansible.builtin.systemd:
    daemon_reload: true
    name: 'apt-daily-upgrade.timer'
    state: 'restarted'
    enabled: yes
...
