# SPDX-FileCopyrightText: Helmholtz Centre for Environmental Research (UFZ)
# SPDX-FileCopyrightText: Helmholtz-Zentrum Dresden-Rossendorf (HZDR)
#
# SPDX-License-Identifier: Apache-2.0

---
dependency:
  name: "galaxy"
driver:
  name: "podman"
platforms:
  - name: "haproxy_v3.2"
    image: "${MOLECULE_IMAGE:-ghcr.io/hifis-net/ubuntu-systemd:24.04}"
    pre_build_image: true
    privileged: true
    override_command: false
    systemd: true
    tty: true
  - name: "haproxy_v3.0"
    image: "${MOLECULE_IMAGE:-ghcr.io/hifis-net/ubuntu-systemd:24.04}"
    pre_build_image: true
    privileged: true
    override_command: false
    systemd: true
    tty: true
  - name: "haproxy_v2.8"
    image: "${MOLECULE_IMAGE:-ghcr.io/hifis-net/ubuntu-systemd:24.04}"
    pre_build_image: true
    privileged: true
    override_command: false
    systemd: true
    tty: true
  - name: "haproxy_v2.6"
    image: "${MOLECULE_IMAGE:-ghcr.io/hifis-net/ubuntu-systemd:24.04}"
    pre_build_image: true
    privileged: true
    override_command: false
    systemd: true
    tty: true
  - name: "haproxy_v2.4"
    image: "${MOLECULE_IMAGE:-ghcr.io/hifis-net/ubuntu-systemd:24.04}"
    pre_build_image: true
    privileged: true
    override_command: false
    systemd: true
    tty: true
provisioner:
  name: "ansible"
  inventory:
    hosts:
      all:
        vars:
          haproxy_ssl_dhparam_size: 512
    host_vars:
      haproxy_v3.2:
        haproxy_create_self_signed_cert: true
        haproxy_ppa_version: "ppa:vbernat/haproxy-3.2"
        haproxy_version: "3.2.*"
      haproxy_v3.0:
        haproxy_create_self_signed_cert: true
        haproxy_ppa_version: "ppa:vbernat/haproxy-3.0"
        haproxy_version: "3.0.*"
      haproxy_v2.8:
        haproxy_create_self_signed_cert: true
        haproxy_ppa_version: "ppa:vbernat/haproxy-2.8"
        haproxy_version: "2.8.*"
      haproxy_v2.6:
        haproxy_create_self_signed_cert: false
        haproxy_ssl_cert_chain_src_file_path: "{{ (lookup('env', 'MOLECULE_SCENARIO_DIRECTORY'), 'test.pem') | path_join }}"
        haproxy_ppa_version: "ppa:vbernat/haproxy-2.6"
        haproxy_version: "2.6.*"
      haproxy_v2.4:
        haproxy_create_self_signed_cert: true
        haproxy_ppa_version: "ppa:vbernat/haproxy-2.4"
        haproxy_version: "2.4.*"
  playbooks:
    prepare: "prepare.yml"
    check: "converge.yml"
    converge: "converge.yml"
    verify: "verify.yml"
verifier:
  name: "ansible"
scenario:
  name: "haproxy"
  test_sequence:
    - "destroy"
    - "dependency"
    - "syntax"
    - "create"
    - "prepare"
    - "check"
    - "converge"
    - "idempotence"
    - "check"
    - "side_effect"
    - "verify"
    - "destroy"

...
