# SPDX-FileCopyrightText: Helmholtz Centre for Environmental Research (UFZ)
# SPDX-FileCopyrightText: Helmholtz-Zentrum Dresden-Rossendorf (HZDR)
#
# SPDX-License-Identifier: GPL-2.0-or-later

---
__unattended_origins_patterns:
  - 'origin=Debian,codename=${distro_codename},label=Debian-Security'
