---
# List of unattended-upgrades options that need to be erased before set by this role
# See https://github.com/hifis-net/ansible-role-unattended-upgrades/issues/94
__clear_options:
  - "Acquire::http::Dl-Limit"
  - "APT::Periodic::Update-Package-Lists"
  - "APT::Periodic::Unattended-Upgrade"
  - "Unattended-Upgrade"
  - "Unattended-Upgrade::Allow-downgrade"
  - "Unattended-Upgrade::Allowed-Origins"
  - "Unattended-Upgrade::Allow-APT-Mark-Fallback"
  - "Unattended-Upgrade::AutoFixInterruptedDpkg"
  - "Unattended-Upgrade::Automatic-Reboot"
  - "Unattended-Upgrade::Automatic-Reboot-Time"
  - "Unattended-Upgrade::Automatic-Reboot-WithUsers"
  - "Unattended-Upgrade::Debug"
  - "Unattended-Upgrade::DevRelease"
  - "Unattended-Upgrade::InstallOnShutdown"
  - "Unattended-Upgrade::Keep-Debs-After-Install"
  - "Unattended-Upgrade::Mail"
  - "Unattended-Upgrade::MailReport"
  - "Unattended-Upgrade::MinimalSteps"
  - "Unattended-Upgrade::OnlyOnACPower"
  - "Unattended-Upgrade::Origins-Pattern"
  - "Unattended-Upgrade::Package-Blacklist"
  - "Unattended-Upgrade::Package-Whitelist"
  - "Unattended-Upgrade::Package-Whitelist-Strict"
  - "Unattended-Upgrade::Remove-New-Unused-Dependencies"
  - "Unattended-Upgrade::Remove-Unused-Dependencies"
  - "Unattended-Upgrade::Remove-Unused-Kernel-Packages"
  - "Unattended-Upgrade::Sender"
  - "Unattended-Upgrade::Skip-Updates-On-Metered-Connections"
  - "Unattended-Upgrade::SyslogEnable"
  - "Unattended-Upgrade::SyslogFacility"
  - "Unattended-Upgrade::Update-Days"
  - "Unattended-Upgrade::Verbose"
